apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'guesbook'
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/ziberini/external.git
        revision: HEAD
        files:
        - path: "dev/config.yaml"
  template:
    metadata:
      name: '{{cluster.name}}-guestbook'
    spec:
      project: default
      source:
        repoURL: https://github.com/ziberini/test-argo.git
        targetRevision: HEAD
        path: "examples/guestbook"
        helm:
          valueFiles:
            - values.yaml
          parameters:
            - name: "image"
              value: '{{guestbook.image}}:{{guestbook.tag}}'
            - name: "environment"
              value: '{{guestbook.labels.environment}}'
      destination:
        # server: https://kubernetes.default.svc
        server: '{{cluster.address}}'
        namespace: dev-guestbook
