apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: 'nginx'
spec:
  generators:
    - git:
        repoURL: https://github.com/ziberini/external.git
        revision: HEAD
        files:
        - path: "dev/config.yaml"
  template:
    metadata:
      name: '{{cluster.name}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://github.com/ziberini/test-argo.git
        targetRevision: HEAD
        path: "examples/nginx/templates"
        helm:
          valueFiles:
            - values.yaml
          # parameters:
          #   - name: image
          #     value: 'nginx'
          #   - name: replicaCount
          #     value: '1'
          #   - name: name
          #     value: 'nginx'
      destination:
        # server: https://kubernetes.default.svc
        server: '{{cluster.address}}'
        namespace: dev-nginx
      
