apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  # labels:
  #   environment: {{ .Values.environment }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - image: {{ .Values.image }}
        name: {{ .Values.name }}
        ports:
        - containerPort: 80