apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
spec:
  generators:
    - git:
        repoURL: https://github.com/ziberini/external.git
        revision: HEAD
        files:
        - path: "examples/git-generator-files-discovery/cluster-config/dev/config.json"
  template:
    metadata:
      name: '{{cluster.name}}-nginx'
    spec:
      project: default
      source:
        repoURL: https://github.com/ziberini/test-argo.git
        targetRevision: HEAD
        path: "examples/nginx"
      destination:
        #server: https://kubernetes.default.svc
        server: '{{cluster.address}}'
        namespace: nginx-2
